---
title: "Compresión de datos usando Análisis de Componentes Principales"
author: "Víctor Gallego y Roi Naveiro"
date: "01/04/2019"
output:
  pdf_document: default
  html_document: default
---

Función auxiliar para mostrar imágenes

```{r, echo=F}
plot_jpeg = function(jpg, add=FALSE)
{
  require('jpeg')
  res = dim(jpg)[2:1] # get the resolution, [x, y]
  if (!add) # initialize an empty plot area if add==FALSE
    plot(1,1,xlim=c(1,res[1]),ylim=c(1,res[2]),asp=1,type='n',xaxs='i',yaxs='i',xaxt='n',yaxt='n',xlab='',ylab='',bty='n')
  rasterImage(jpg,1,1,res[1],res[2])
}
```

Leemos la imagen.

```{r, echo=F}
library(jpeg)
ine = readJPEG("ine.jpg")
plot_jpeg(ine)
```

Haremos análisis de componentes principales en cada canal

```{r, echo=F}
r = ine[,,1]
g = ine[,,2]
b = ine[,,3]
##
ine.r.pca <- prcomp(r, center = FALSE)
ine.g.pca <- prcomp(g, center = FALSE)
ine.b.pca <- prcomp(b, center = FALSE)
##
rgb.pca <- list(ine.r.pca, ine.g.pca, ine.b.pca)
```

Comprimimos escogiendo un número M de componentes principales

```{r, echo=F}
compress = function(M=1200, pca_obj){
  pca.img <- sapply(pca_obj, function(j) {
    compressed.img <- j$x[,1:M] %*% t(j$rotation[,1:M])
  }, simplify = 'array')
  pca.img[pca.img<0] = 0
  pca.img[pca.img>1] = 1
  return(pca.img)
}
```


